### ISSUE TITLE
Syntax highlighting of code examples in doc tests are not stopped

### ISSUE THREAD

**Issue by zzeroo** [TheEnigmaBlade/atom-language-rust-redux#1]
Syntax highlighting of code examples in doc tests are not stopped.

This happens with the latest master git repo.

![atom-language-rust-redox](https://cloud.githubusercontent.com/assets/61134/20304016/6ab19730-ab2e-11e6-8e7f-34a9d4360c6a.png)

**Comment by TheEnigmaBlade** [comment]
Seems the issue occurs when code is placed on the line directly below an empty doc comment line. It does not occur if there is a blank line between comment and code, there is other text on the last comment line, or with normal non-doc comments.

Interestingly, it's entirely unrelated to code blocks. Once I correct all the tests for the new behavior, I'll make a new build.
