### ISSUE TITLE
Syntax highlighting of RustDoc code samples in block quotes is not stopped

### ISSUE THREAD

**Issue by hawkw** [TheEnigmaBlade/atom-language-rust-redux#2]
Similar to issue #1, when a fenced code sample appears inside a RustDoc block quote, the entire rest of the file is highlighted as a comment.

For example:
<img width="681" alt="screen shot 2017-07-25 at 2 24 42 pm" src="https://user-images.githubusercontent.com/2796466/28589812-457bc17e-7145-11e7-9ed0-aa6b9fdbc7e7.png">
Deleting the last `>` character in the block quote fixes this issue:
<img width="629" alt="screen shot 2017-07-25 at 2 26 45 pm" src="https://user-images.githubusercontent.com/2796466/28589832-5b0c477a-7145-11e7-8482-a336c27b0f13.png">

**Comment by TheEnigmaBlade** [comment]
Should be fixed with 7307ce37c70c8ca326955d91fb8adadce9c82552 in 0.2.2.
