### ISSUE TITLE
Syntax highlighting of RustDoc containing underscores is not stopped

### ISSUE THREAD

**Issue by hawkw** [TheEnigmaBlade/atom-language-rust-redux#3]
Yet another RustDoc highlighting issue! This time, when a RustDoc comment contains an underscore character, following code after the termination of the comment is also highlighted as comments. 

### Screenshots

Incorrect highlighting:
<img width="335" alt="screen shot 2017-09-06 at 10 25 12 am" src="https://user-images.githubusercontent.com/2796466/30120182-c05223f6-92ed-11e7-89d0-022dfab900e4.png">

After deleting the underscore:
<img width="332" alt="screen shot 2017-09-06 at 10 25 28 am" src="https://user-images.githubusercontent.com/2796466/30120209-cf86db46-92ed-11e7-8784-576c7659e994.png">

**Comment by TheEnigmaBlade** [comment]
Fixed the issue, although I reviewed [RFC #505] and don't see a mention of inline styles other than "Markdown". They might need to be removed.

[RFC #505]: https://github.com/rust-lang/rfcs/blob/master/text/0505-api-comment-conventions.md
